language: node_js
node_js:
  - "stable"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g gulp
  - npm install -g karma
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install
  - ./nodeserver.sh > /dev/null &

script:
  - gulp

sudo: false

git:
  depth: 10
